package io.github.routeforge.core.type;

import io.github.routeforge.core.analyzer.Row;
import io.github.routeforge.core.repository.RouteRepository;
import io.github.routeforge.core.support.HttpMethods;
import io.github.routeforge.core.support.JsonWriter;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * TS 类型声明与 JSON 结构生成器（{@code --forge:types} 的输出层，SPEC §3.2）。
 *
 * <p>框架无关：输入是分析器已经产出的行（{@link Row}）＋目标层级列表，本类只做纯文本生成。
 * 生成的 d.ts 通过 module augmentation 增强 {@code @route-forge/core} 的 {@code ForgeRouteMap}，
 * 让前端 composable 自动获得路由名与参数的类型推断。
 *
 * <p>逐行与 PHP 侧 {@code RouteForge\Common\Type\TypeGenerator} 对齐，包括排版细节
 * （缩进、空行、分隔线注释的宽度）——这些是产物文本的一部分，对等测试按整文比对。
 */
public final class TypeGenerator {

    /** 带 body 的 HTTP 方法（其余视为无 body）。 */
    private static final List<String> BODY_METHODS = List.of("POST", "PUT", "PATCH");

    /** URL 模板里的可选参数标记：{@code {param?}}。 */
    private static final Pattern OPTIONAL_PARAM = Pattern.compile("\\{(\\w+)\\?}");

    /** 无需加引号即可作为 TS 对象键的形态。 */
    private static final Pattern BARE_KEY = Pattern.compile("^[A-Za-z_][A-Za-z0-9_]*$");

    /**
     * 单条路由的类型素材。
     *
     * @param optionalParams 由 URI 模板 {@code {p?}} 得到的可选参数名——TS 的 {@code ?} 只看它，
     *                       与是否有默认值无关（默认值经 {@code parameter_defaults} 独立下发）
     */
    public record TypeEntry(String method, List<String> params, List<String> optionalParams,
                            Map<String, Object> defaults, boolean hasBody, String response) {

        public TypeEntry {
            params = List.copyOf(params);
            optionalParams = List.copyOf(optionalParams);
        }
    }

    /**
     * 从分析器的行组装「层级 → 路由名 → 类型素材」二维映射。
     *
     * <p>三条过滤规则缺一不可：未归级（{@code tier == null}）的行不生成类型（无层级归属）；
     * 不在目标层级列表里的行跳过（{@code --level} 过滤时不能让 d.ts 仍冒出别的层级块）；
     * 目标层级即便 0 路由也要预置空映射，保证 {@code ForgeLevel} 联合类型覆盖全部已配置层级，
     * 前端引用空层级不会 TS 报错。
     */
    public Map<String, Map<String, TypeEntry>> collectTargets(List<Row> rows, List<String> targets) {
        Map<String, Map<String, TypeEntry>> byLevel = new LinkedHashMap<>();
        targets.forEach(target -> byLevel.put(target, new LinkedHashMap<>()));

        for (Row row : rows) {
            if (row.tier() == null || !byLevel.containsKey(row.level())) {
                continue;
            }
            List<String> methods = HttpMethods.withoutHead(row.methods());
            String method = methods.isEmpty() ? "GET" : methods.get(0).toUpperCase();

            byLevel.get(row.level()).put(row.name(), new TypeEntry(method, row.parameters(),
                    extractOptionalParams(row.uri()), row.parameterDefaults(),
                    BODY_METHODS.contains(method), "unknown"));
        }
        return byLevel;
    }

    /**
     * 生成 d.ts 全文，时间戳按 PHP 侧同源规则取当前时刻。
     *
     * <p>PHP 是 {@code date('Y-m-d\TH:i:s.000\Z')}：毫秒位恒为字面量 {@code .000}、{@code Z} 也是字面量、
     * 时区取进程默认。也就是说非 UTC 机器上它会写出「本地时间 + Z」这种名不副实的后缀——
     * 这是上游既有行为，本类照抄而不是「顺手修正」，否则同一份路由表在两个后端上生成的文件头会不同。
     */
    public String generateDts(Map<String, Map<String, TypeEntry>> routesByLevel, String endpointPrefix) {
        return generateDts(routesByLevel, endpointPrefix, currentTimestamp());
    }

    /** 与 PHP {@code date('Y-m-d\TH:i:s.000\Z')} 同形态的时间戳（本地时区 + 字面量毫秒与 Z）。 */
    public static String currentTimestamp() {
        return java.time.LocalDateTime.now()
                .format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss'.000Z'"));
    }

    /**
     * 生成 d.ts 全文（时间戳可注入，便于复现与对等测试）。
     *
     * @param routesByLevel {@link #collectTargets} 的产物
     * @param endpointPrefix 实际端点前缀（与端点注册同一规范化），写进文件头注释
     * @param timestamp      时间戳串，形态见 {@link #currentTimestamp()}
     */
    public String generateDts(Map<String, Map<String, TypeEntry>> routesByLevel, String endpointPrefix,
            String timestamp) {
        List<String> lines = new ArrayList<>();
        List<String> levels = routesByLevel.keySet().stream().map(level -> level.isEmpty() ? "unassigned" : level)
                .toList();

        lines.add("// AUTO-GENERATED by route:forge:types. Do not edit.");
        lines.add("// 生成时间: " + timestamp);
        lines.add("// 端点: " + endpointPrefix);
        lines.add("import { ForgeRouteMap } from \"@route-forge/core\";");
        lines.add("");
        lines.add("// ─── 层级名联合类型 ───────────────────────────────────────────");
        lines.add("export type ForgeLevel = " + (levels.isEmpty() ? "never"
                : levels.stream().map(level -> "'" + level + "'").reduce((a, b) -> a + " | " + b).orElse("never"))
                + ";");
        lines.add("");
        lines.add("// ─── 各层级路由名联合类型 ─────────────────────────────────────");
        lines.add("export type ForgeRouteName<L extends ForgeLevel> = L extends keyof ForgeRouteMap");
        lines.add("  ? keyof ForgeRouteMap[L] & string");
        lines.add("  : never;");
        lines.add("");
        lines.add("// ─── 单条路由元信息（端点返回的 routes 值结构） ────────────────────");
        lines.add("export interface ForgeRouteMeta {");
        lines.add("  method: string;");
        lines.add("  uri: string;");
        lines.add("  parameters: string[];");
        lines.add("  parameter_defaults: Record<string, unknown>;");
        lines.add("}");
        lines.add("");
        lines.add("// ─── 按层级 → 路由名 → 类型约束的映射 ────────────────────────");
        lines.add("// 通过 module augmentation 增强 @route-forge/core 的 ForgeRouteMap，");
        lines.add("// 使 useForge / useForgeApi 自动获得路由名和参数的类型推断。");
        lines.add("// ⚠ 依赖 @route-forge/core 包，请确保前端项目已安装该依赖。");
        lines.add("");
        lines.add("declare module '@route-forge/core' {");
        lines.add("  interface ForgeRouteMap {");

        routesByLevel.forEach((level, routes) -> {
            String levelKey = level.isEmpty() ? RouteRepository.UNASSIGNED_LEVEL : level;
            lines.add("    " + quoteKey(levelKey) + ": {");
            routes.forEach((name, entry) -> {
                List<String> fields = paramsFields(entry.params(), entry.optionalParams());
                String paramsBlock = fields.isEmpty() ? "{}"
                        : "{\n" + String.join("\n", fields) + "\n      }";
                lines.add("      " + quoteKey(name) + ": {");
                lines.add("        method: '" + entry.method() + "';");
                lines.add("        params: " + paramsBlock + ";");
                if (entry.hasBody()) {
                    lines.add("        body: unknown;");
                }
                lines.add("        response: " + entry.response() + ";");
                lines.add("      };");
            });
            lines.add("    };");
            lines.add("");
        });

        lines.add("  }");
        lines.add("}");
        lines.add("");
        lines.add("// ─── 本地别名（向后兼容） ──────────────────────────────────────");
        lines.add("export type ForgeRoutes = ForgeRouteMap;");
        lines.add("");
        lines.add("// ─── 工具类型：从 ForgeRouteMap 提取具体字段 ────────────────────");
        lines.add("");
        lines.add("/** 提取指定层级 + 路由名的 method */");
        lines.add("export type ForgeMethod<");
        lines.add("  L extends ForgeLevel,");
        lines.add("  N extends ForgeRouteName<L>,");
        lines.add("> = L extends keyof ForgeRouteMap");
        lines.add("  ? N extends keyof ForgeRouteMap[L] ? ForgeRouteMap[L][N]['method'] : never");
        lines.add("  : never;");
        lines.add("");
        lines.add("/** 提取指定层级 + 路由名的路径参数 */");
        lines.add("export type ForgeParams<");
        lines.add("  L extends ForgeLevel,");
        lines.add("  N extends ForgeRouteName<L>,");
        lines.add("> = L extends keyof ForgeRouteMap");
        lines.add("  ? N extends keyof ForgeRouteMap[L] ? ForgeRouteMap[L][N]['params'] : never");
        lines.add("  : never;");
        lines.add("");
        lines.add("/** 提取指定层级 + 路由名的 body 类型（GET/DELETE 为 never） */");
        lines.add("export type ForgeBody<");
        lines.add("  L extends ForgeLevel,");
        lines.add("  N extends ForgeRouteName<L>,");
        lines.add("> = L extends keyof ForgeRouteMap");
        lines.add("  ? N extends keyof ForgeRouteMap[L]");
        lines.add("    ? 'body' extends keyof ForgeRouteMap[L][N]");
        lines.add("      ? ForgeRouteMap[L][N]['body']");
        lines.add("      : never");
        lines.add("    : never");
        lines.add("  : never;");
        lines.add("");
        lines.add("/** 提取指定层级 + 路由名的 response 类型 */");
        lines.add("export type ForgeResponse<");
        lines.add("  L extends ForgeLevel,");
        lines.add("  N extends ForgeRouteName<L>,");
        lines.add("> = L extends keyof ForgeRouteMap");
        lines.add("  ? N extends keyof ForgeRouteMap[L] ? ForgeRouteMap[L][N]['response'] : never");
        lines.add("  : never;");
        lines.add("");

        return String.join("\n", lines);
    }

    /**
     * 生成 JSON 产物（二级结构：层级 → 路由名）。
     *
     * <p>{@code parameter_defaults} 仅在有默认值时出现、{@code body} 仅在带 body 的方法上出现——命令行与
     * 脚本按键是否存在做判断，多一个键就是一次契约变更。
     *
     * <p>照抄上游的一处偶然形态：<b>目标层级为 0 时顶层输出 {@code []} 而不是 {@code {}}</b>
     * （PHP 侧顶层没做 {@code (object)} 强转，只有每个层级块做了）。层级块本身空仍为 {@code {}}，
     * 那是「按路由名索引的对象」契约所在。已在 SPEC 注明，脚本侧要能容忍顶层两种形态。
     */
    public String generateJson(Map<String, Map<String, TypeEntry>> routesByLevel) {
        Map<String, Object> out = new LinkedHashMap<>();

        routesByLevel.forEach((level, routes) -> {
            Map<String, Object> levelData = new LinkedHashMap<>();
            routes.forEach((name, entry) -> {
                Map<String, Object> item = new LinkedHashMap<>();
                item.put("method", entry.method());
                item.put("params", entry.params());
                if (!entry.defaults().isEmpty()) {
                    item.put("parameter_defaults", entry.defaults());
                }
                if (entry.hasBody()) {
                    item.put("body", "unknown");
                }
                item.put("response", entry.response());
                levelData.put(name, item);
            });
            out.put(level.isEmpty() ? RouteRepository.UNASSIGNED_LEVEL : level, levelData);
        });

        return JsonWriter.pretty(out.isEmpty() ? List.of() : out);
    }

    /**
     * 从 URI 模板提取可选参数名（{@code {param?}} 语法）。供命令层在收集阶段调用。
     *
     * <p>只认 {@code \w+}：Spring 的 {@code {id:\d+}} 这类带约束的模板必须先在适配层剥离约束，
     * 到不了这里（前端占位符正则也不认冒号）。
     */
    public List<String> extractOptionalParams(String uri) {
        List<String> names = new ArrayList<>();
        Matcher matcher = OPTIONAL_PARAM.matcher(uri);
        while (matcher.find()) {
            names.add(matcher.group(1));
        }
        return names;
    }

    private static List<String> paramsFields(List<String> params, List<String> optionalParams) {
        List<String> fields = new ArrayList<>();
        for (String param : params) {
            String optional = optionalParams.contains(param) ? "?" : "";
            fields.add("        " + param + optional + ": string | number;");
        }
        return fields;
    }

    /** 仅含特殊字符的键才加引号（与 PHP 侧同规则，用 JSON 编码作为引号形态）。 */
    private static String quoteKey(String name) {
        return BARE_KEY.matcher(name).find() ? name : JsonWriter.compact(name);
    }
}
